project:
  type: book
  output-dir: _book
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"

book:
  title: "Data Science Foundations and Machine Learning with R: From Data to Decisions"
  author: "[<span style='color:gray'>Reza Mohammadi</span>](https://www.uva.nl/profile/a.mohammadi)"
  date: today
  date-format: "D MMMM YYYY"
  reader-mode: true

  page-footer:
    left: |
      Data Science Foundations and Machine Learning with R was written by [<span style='color:gray'>Reza Mohammadi</span>](https://www.uva.nl/profile/a.mohammadi).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  search: true
  cover-image: images/logo.png
  favicon: images/logo.png
  site-url: https://uncovering-data-science.netlify.app
  repo-url: https://github.com/RezaMoammadi/Book-Data-Science
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  
  sidebar:
    search: true
    style: docked
    background: light

  chapters:
    - index.qmd
    - 0-preface.qmd
    - 1-Intro-R.qmd
    - 2-Intro-data-science.qmd
    - 3-Data-preparation.qmd
    - 4-Exploratory-data-analysis.qmd
    - 5-Statistics.qmd
    - 6-Setup-data.qmd
    - 7-Classification-kNN.qmd
    - 8-Model-evaluation.qmd
    - 9-Naive-Bayes.qmd
    - 10-Regression.qmd
    - 11-Tree-based-models.qmd
    - 12-Neural-networks.qmd
    - 13-Clustering.qmd
    - 14-References.qmd

bibliography: [references.bib, packages.bib]

format:
  html:
    number-sections: true
    toc: true
    theme:
      - cosmo
      - r4ds.scss
    code-fold: false
    code-link: true
    author-meta: "Reza Mohammadi"
    include-in-header: "plausible.html"
    theorem-environments:
      - name: example
        title: "Example"
        numbered: true
        counter-depth: 2
 
  pdf:
    pdf-engine: xelatex # or lualatex
    documentclass: svmono
    mainfont: "Palatino"
    monofont: "Inconsolata"
    code-block: true
    code-block-font-size: 7pt
    include-in-header: template.tex
    number-sections: true
    toc: true
    keep-tex: true
    theorem-environments:
      - name: example
        title: "Example"
        numbered: true
        counter-depth: 2
    callout-definitions:
      example:
        title: "Example"
        color: "gray!10"

editor: visual

